name: enso-iod-2ma
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy>=1.26.4
  - pandas>=2.1.4
  - xarray>=2025.1.2
  - matplotlib>=3.10.0
  - cartopy>=0.24.1
  - scipy>=1.15.1
  - netCDF4>=1.7.2
  - cftime>=1.6.4
  - seaborn>=0.13.2
  - cmocean>=4.0.3
  - nc-time-axis>=1.4.1
  - eofs>=2.0.0
  - statsmodels>=0.14.4
  - scikit-learn>=1.6.1
  - rasterio>=1.4.3
  - geopandas>=1.0.1
  - shapely>=2.0.7
  - opencv
  - jupyter
  - ipykernel
  - h5netcdf>=1.5.0
  - dask>=2025.1.0
  - tqdm>=4.67.1
  - regionmask>=0.13.0
  - pip
  - pip:
    - ultraplot>=1.0.3
    - pop-tools>=2023.6.0
    - git+https://github.com/jswhit/pyspharm@a464ebfed334188fc0ef275fad4aafd2d9fa716e
    - git+https://github.com/ajdawson/windspharm@53500a83b0d5024169ec74313af52f840a693a36

